// Code generated by go-swagger; DO NOT EDIT.

package archive

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetYearMonthJSONParams creates a new GetYearMonthJSONParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetYearMonthJSONParams() *GetYearMonthJSONParams {
	return &GetYearMonthJSONParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetYearMonthJSONParamsWithTimeout creates a new GetYearMonthJSONParams object
// with the ability to set a timeout on a request.
func NewGetYearMonthJSONParamsWithTimeout(timeout time.Duration) *GetYearMonthJSONParams {
	return &GetYearMonthJSONParams{
		timeout: timeout,
	}
}

// NewGetYearMonthJSONParamsWithContext creates a new GetYearMonthJSONParams object
// with the ability to set a context for a request.
func NewGetYearMonthJSONParamsWithContext(ctx context.Context) *GetYearMonthJSONParams {
	return &GetYearMonthJSONParams{
		Context: ctx,
	}
}

// NewGetYearMonthJSONParamsWithHTTPClient creates a new GetYearMonthJSONParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetYearMonthJSONParamsWithHTTPClient(client *http.Client) *GetYearMonthJSONParams {
	return &GetYearMonthJSONParams{
		HTTPClient: client,
	}
}

/*
GetYearMonthJSONParams contains all the parameters to send to the API endpoint

	for the get year month JSON operation.

	Typically these are written to a http.Request.
*/
type GetYearMonthJSONParams struct {

	/* Month.

	   Year: 1-12

	   Default: 9
	*/
	Month int64

	/* Year.

	   Year: 1851-2019

	   Default: 2018
	*/
	Year int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get year month JSON params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetYearMonthJSONParams) WithDefaults() *GetYearMonthJSONParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get year month JSON params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetYearMonthJSONParams) SetDefaults() {
	var (
		monthDefault = int64(9)

		yearDefault = int64(2018)
	)

	val := GetYearMonthJSONParams{
		Month: monthDefault,
		Year:  yearDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get year month JSON params
func (o *GetYearMonthJSONParams) WithTimeout(timeout time.Duration) *GetYearMonthJSONParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get year month JSON params
func (o *GetYearMonthJSONParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get year month JSON params
func (o *GetYearMonthJSONParams) WithContext(ctx context.Context) *GetYearMonthJSONParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get year month JSON params
func (o *GetYearMonthJSONParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get year month JSON params
func (o *GetYearMonthJSONParams) WithHTTPClient(client *http.Client) *GetYearMonthJSONParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get year month JSON params
func (o *GetYearMonthJSONParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMonth adds the month to the get year month JSON params
func (o *GetYearMonthJSONParams) WithMonth(month int64) *GetYearMonthJSONParams {
	o.SetMonth(month)
	return o
}

// SetMonth adds the month to the get year month JSON params
func (o *GetYearMonthJSONParams) SetMonth(month int64) {
	o.Month = month
}

// WithYear adds the year to the get year month JSON params
func (o *GetYearMonthJSONParams) WithYear(year int64) *GetYearMonthJSONParams {
	o.SetYear(year)
	return o
}

// SetYear adds the year to the get year month JSON params
func (o *GetYearMonthJSONParams) SetYear(year int64) {
	o.Year = year
}

// WriteToRequest writes these params to a swagger request
func (o *GetYearMonthJSONParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param month
	if err := r.SetPathParam("month", swag.FormatInt64(o.Month)); err != nil {
		return err
	}

	// path param year
	if err := r.SetPathParam("year", swag.FormatInt64(o.Year)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
