// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Byline byline
//
// swagger:model Byline
type Byline struct {

	// organization
	Organization string `json:"organization,omitempty"`

	// original
	Original string `json:"original,omitempty"`

	// person
	Person []*Person `json:"person"`
}

// Validate validates this byline
func (m *Byline) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePerson(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Byline) validatePerson(formats strfmt.Registry) error {
	if swag.IsZero(m.Person) { // not required
		return nil
	}

	for i := 0; i < len(m.Person); i++ {
		if swag.IsZero(m.Person[i]) { // not required
			continue
		}

		if m.Person[i] != nil {
			if err := m.Person[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("person" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("person" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this byline based on the context it is used
func (m *Byline) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePerson(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Byline) contextValidatePerson(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Person); i++ {

		if m.Person[i] != nil {

			if swag.IsZero(m.Person[i]) { // not required
				return nil
			}

			if err := m.Person[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("person" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("person" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Byline) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Byline) UnmarshalBinary(b []byte) error {
	var res Byline
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
