// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Headline headline
//
// swagger:model Headline
type Headline struct {

	// content kicker
	ContentKicker string `json:"content_kicker,omitempty"`

	// kicker
	Kicker string `json:"kicker,omitempty"`

	// main
	Main string `json:"main,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// print headline
	PrintHeadline string `json:"print_headline,omitempty"`

	// seo
	Seo string `json:"seo,omitempty"`

	// sub
	Sub string `json:"sub,omitempty"`
}

// Validate validates this headline
func (m *Headline) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this headline based on context it is used
func (m *Headline) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Headline) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Headline) UnmarshalBinary(b []byte) error {
	var res Headline
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
