// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Keyword keyword
//
// swagger:model Keyword
type Keyword struct {

	// major
	Major string `json:"major,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// rank
	Rank int64 `json:"rank,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this keyword
func (m *Keyword) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this keyword based on context it is used
func (m *Keyword) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Keyword) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Keyword) UnmarshalBinary(b []byte) error {
	var res Keyword
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
